### ISSUE TITLE
Script Runs on Sepolia but not Hyperspace

### ISSUE THREAD

**Issue by ZakAyesh** [glifio/filecoin-iac#153]
Repo: https://github.com/xBalbinus/fevm-foundry-kit#interact-with-the-contracts

I am trying to run the following command using the above repo:

` forge script script/SimpleCoin.s.sol:MyScript --rpc-url https://api.hyperspace.node.glif.io/rpc/v1 --broadcast --verify -vvvv `

However, this results in a gas limit error:
[See transaction here on Filfox](https://hyperspace.filfox.info/en/message/bafy2bzacebtpeioefo5yo3aufkm76lodrw22niq6tkmewgpmngpn3svsl3x3i)

So I manually upped the gas limit (around 50x multiplier) using the command below:

` forge script script/SimpleCoin.s.sol:MyScript --rpc-url https://api.hyperspace.node.glif.io/rpc/v1 --broadcast --verify -vvvv -g 5000 `

And the script still errored out with a generic error:
[See transaction here on Filfox](https://hyperspace.filfox.info/en/message/bafy2bzacebijjaxfuvqk5j32rt5oewy563vuqsvgvmbczdnho2vy43mdeqeoi)

However, when the original script is run against Sepolia it runs fine. This indicated something may be off with the rpc and Foundry.

**Comment by ZakAyesh** [comment]
It may have something to do with the fact that Foundry simulates the transaction in a local VM first. Running the command below gets the transaction on-chain, but still returns a "transactions dropped from mempool" error.

New command: ` forge script script/SimpleCoin.s.sol:MyScript --rpc-url https://api.hyperspace.node.glif.io/rpc/v1 --broadcast --skip-simulation `

[Transaction on Hyperspace](https://hyperspace.filfox.info/en/message/bafy2bzaceataiq7mvuudgy4hbcydh23n42f4eh2tqec4sy4qab546dvz2gjbs)

Error received by script:
Error: 
Transaction dropped from the mempool: 0x01e17502ae5794795fe08c6b375538cb46462b6f068b80e6b4291ac6eea4a199
Transaction dropped from the mempool: 0x2f43ab6d67dbf52de5822420605c4c8f0840638fc21a85fbd294b852d56bd3b2

**Comment by ArseniiPetrovich** [comment]
According to the script:
`Estimated total gas used for script: 13674950`
Instead of skipping the simulation you can simply increase the gas limit not using `-g` parameter, but using `--gas-limit`.

After digging into Foundry I've figured out that Foundry first checks for TX status and if it is not confirmed - checks the mempool for transactions:
 https://github.com/foundry-rs/foundry/blob/master/cli/src/cmd/forge/script/receipts.rs#L140
 
 If there are no transaction there - it throws the error. 
 However, I was not able to identify why it considers TX mempool empty. The strange thing I noticed is that there is a difference output between Sepolia and Hyperspace for `eth_newPendingTransactionFilter` method.
 Sepolia returns:
 ```
 {
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x94c95e781ac74b7481cd3b81c29029a1"
}
```
 While Hyperspace returns smth like:
 ```
 {
    "jsonrpc": "2.0",
    "result": "0xc951a53d0cac4038b1c8a27a32a7b91200000000000000000000000000000000",
    "id": 1
}
```

These 0000 in the end is something I have concerns about. I'm closing this task as further debugging would require significant amount of time and is not directly connected with Glif, but with Lotus application itself and/or Foundry way of transactions verifications.
